# Generated by Django 4.2.7 on 2024-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_info', models.CharField(max_length=200, null=True)),
                ('car_owner', models.CharField(max_length=200, null=True)),
                ('strike_chart', models.ImageField(blank=True, upload_to='recipt_strike/')),
                ('recipient', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
