# Generated by Django 4.2.7 on 2024-07-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Vouchers',
        ),
    ]
