# Generated by Django 4.2.7 on 2024-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0002_rename_drivers_vouchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('strike_chart', models.ImageField(blank=True, upload_to='recipt_att/')),
            ],
        ),
        migrations.AddField(
            model_name='vouchers',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
