# Generated by Django 4.2.7 on 2024-07-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0003_attachments_vouchers_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='number',
        ),
        migrations.AddField(
            model_name='attachments',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipt_vouchers.vouchers'),
        ),
    ]
