# Generated by Django 4.2.7 on 2024-07-18 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0004_remove_attachments_number_attachments_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='car_info',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='car_mark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='car_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='car_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='strike_chart',
            field=models.ImageField(blank=True, null=True, upload_to='recipt_att/'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='car_owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='strike_chart',
            field=models.ImageField(blank=True, null=True, upload_to='recipt_strike/'),
        ),
    ]
