# Generated by Django 4.2.7 on 2024-07-18 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0005_remove_vouchers_car_info_vouchers_car_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
