# Generated by Django 4.2.7 on 2024-07-18 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0006_alter_vouchers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
