# Generated by Django 4.2.7 on 2024-07-18 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0007_alter_vouchers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
