# Generated by Django 4.2.7 on 2024-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0008_alter_vouchers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='recipient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
