# Generated by Django 4.2.7 on 2024-07-20 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0009_alter_vouchers_location_alter_vouchers_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouchers',
            old_name='created_by',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='vouchers',
            old_name='location',
            new_name='receipt_from_location',
        ),
        migrations.RenameField(
            model_name='vouchers',
            old_name='created_at',
            new_name='receipt_from_time',
        ),
        migrations.RenameField(
            model_name='vouchers',
            old_name='recipient',
            new_name='recipient_from_name',
        ),
        migrations.RemoveField(
            model_name='vouchers',
            name='date',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='receipt_from_signature',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_from_signatures/'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='receipt_to_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='receipt_to_signature',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_to_signatures/'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='receipt_to_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='recipient_to_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
