# Generated by Django 4.2.7 on 2024-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0010_rename_created_by_vouchers_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachments',
            name='driver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='receipt_from_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='receipt_to_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
