# Generated by Django 4.2.7 on 2024-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0011_attachments_created_at_attachments_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='invoice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
