# Generated by Django 4.2.7 on 2024-08-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoices_driver'),
        ('recipt_vouchers', '0013_alter_vouchers_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices'),
        ),
    ]
