# Generated by Django 4.2.7 on 2024-08-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0014_alter_vouchers_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attachments',
            name='driver_name',
        ),
    ]
