# Generated by Django 4.2.7 on 2024-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0016_alter_vouchers_receipt_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='receipt_from_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='receipt_to_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
