# Generated by Django 4.2.7 on 2024-08-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0017_alter_vouchers_receipt_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='exported',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
