# Generated by Django 4.2.7 on 2024-08-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0018_vouchers_exported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='exported',
        ),
    ]
