# Generated by Django 4.2.7 on 2024-08-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0020_alter_vouchers_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='car_owner',
        ),
    ]
