# Generated by Django 4.2.7 on 2024-08-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_customer_vehicles'),
        ('recipt_vouchers', '0021_remove_vouchers_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='car_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
