# Generated by Django 4.2.7 on 2024-08-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0022_vouchers_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
