# Generated by Django 4.2.7 on 2024-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt_vouchers', '0023_attachments_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='receipt_from_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='receipt_to_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
