# Generated by Django 4.2.7 on 2024-07-26 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_treasury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True)),
                ('vehicle', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('supplier', models.IntegerField(blank=True, null=True)),
                ('dinar', models.IntegerField(blank=True, null=True)),
                ('fils', models.IntegerField(blank=True, null=True)),
                ('tamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('samount', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('udinar', models.IntegerField(blank=True, null=True)),
                ('ufils', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('adinar', models.IntegerField(blank=True, null=True)),
                ('afils', models.IntegerField(blank=True, null=True)),
                ('number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.invoices')),
            ],
        ),
    ]
