# Generated by Django 4.2.7 on 2024-07-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_invoices_mainitems_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='number',
            new_name='invoice',
        ),
    ]
