# Generated by Django 4.2.7 on 2024-07-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_rename_number_items_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='invoices',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='vehicle',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
