# Generated by Django 4.2.7 on 2024-07-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
        ('suppliers', '0006_invoices_notes_alter_invoices_dinar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.used_vehicle'),
        ),
    ]
