# Generated by Django 4.2.7 on 2024-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_items_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='adinar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='afils',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='udinar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='ufils',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
