# Generated by Django 4.2.7 on 2024-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
