# Generated by Django 4.2.7 on 2024-08-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_supplier_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='customer',
            new_name='supplier',
        ),
    ]
