# Generated by Django 4.2.7 on 2024-08-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_items_created_at_items_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='payment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
