# Generated by Django 4.2.7 on 2024-08-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_treasury_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='supplier',
        ),
        migrations.AddField(
            model_name='papers',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.invoices'),
        ),
    ]
