# Generated by Django 4.2.7 on 2024-08-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_remove_papers_supplier_papers_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.invoices'),
        ),
    ]
