# Generated by Django 4.2.7 on 2024-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_treasury_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
