# Generated by Django 4.2.7 on 2024-09-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_invoices_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='adinar',
        ),
        migrations.RemoveField(
            model_name='items',
            name='afils',
        ),
        migrations.RemoveField(
            model_name='items',
            name='udinar',
        ),
        migrations.RemoveField(
            model_name='items',
            name='ufils',
        ),
        migrations.AddField(
            model_name='items',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='tamount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
