# Generated by Django 4.2.7 on 2024-09-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_remove_items_adinar_remove_items_afils_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='dinar',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='fils',
        ),
    ]
