# Generated by Django 4.2.7 on 2024-11-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_remove_invoices_dinar_remove_invoices_fils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
