# Generated by Django 4.2.7 on 2024-06-22 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.IntegerField(blank=True, null=True)),
                ('driver_name', models.CharField(max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, null=True, unique=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('require', models.CharField(max_length=200, null=True)),
                ('dinar', models.IntegerField(blank=True, null=True)),
                ('fils', models.IntegerField(blank=True, null=True)),
                ('tamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('samount', models.CharField(max_length=200, null=True)),
                ('car', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udinar', models.IntegerField(blank=True, null=True)),
                ('ufils', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('adinar', models.IntegerField(blank=True, null=True)),
                ('afils', models.IntegerField(blank=True, null=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoices', to_field='number')),
            ],
        ),
    ]
