# Generated by Django 4.2.7 on 2024-06-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
