# Generated by Django 4.2.7 on 2024-07-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_items_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices'),
        ),
    ]
