# Generated by Django 4.2.7 on 2024-07-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_items_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='driver',
        ),
    ]
