# Generated by Django 4.2.7 on 2024-07-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoices_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='driver_name',
            new_name='driver',
        ),
    ]
