# Generated by Django 4.2.7 on 2024-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_driver_name_invoices_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='vehicle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
