# Generated by Django 4.2.7 on 2024-07-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoices_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='require_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
