# Generated by Django 4.2.7 on 2024-07-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoices_require_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='require',
        ),
    ]
