# Generated by Django 4.2.7 on 2024-07-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customers_name'),
        ('invoices', '0008_remove_invoices_require'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='require_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customers'),
        ),
    ]
