# Generated by Django 4.2.7 on 2024-08-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_rename_vehicle_date_used_vehicle_date_and_more'),
        ('invoices', '0009_alter_invoices_require_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.used_vehicle'),
        ),
    ]
