# Generated by Django 4.2.7 on 2024-08-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoices_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='exported',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
