# Generated by Django 4.2.7 on 2024-08-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_customer_vehicles'),
        ('invoices', '0012_invoices_exported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='car',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='require_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
