# Generated by Django 4.2.7 on 2024-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_invoices_car_alter_invoices_require_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='car',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
