# Generated by Django 4.2.7 on 2024-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_invoices_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='dinar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='fils',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='samount',
            field=models.CharField(default='فقط وقدره صفر دينار لا غير', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='tamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
