# Generated by Django 4.2.7 on 2024-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoices_dinar_alter_invoices_fils_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
