# Generated by Django 4.2.7 on 2024-08-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_invoices_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='paid',
            new_name='driver_paid',
        ),
        migrations.AddField(
            model_name='invoices',
            name='customer_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
