# Generated by Django 5.1.4 on 2025-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_alter_invoices_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='currency_code',
            field=models.CharField(default='JOD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_type_code',
            field=models.CharField(default='011', max_length=10),
        ),
        migrations.AddField(
            model_name='invoices',
            name='payment_method',
            field=models.CharField(default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='items',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
