# Generated by Django 5.1.4 on 2025-03-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_invoices_currency_code_invoices_invoice_type_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoices'),
        ),
    ]
