# Generated by Django 5.1.4 on 2025-03-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_alter_items_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='invoice_type_code',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='items',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='items',
            name='tax_percent',
        ),
        migrations.AddField(
            model_name='invoices',
            name='fotarah_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoices',
            name='fotarah_success',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices'),
        ),
        migrations.CreateModel(
            name='FotarahResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('message', models.TextField()),
                ('fotarah_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('qr_code_binary', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices')),
            ],
        ),
    ]
