# Generated by Django 5.1.4 on 2025-04-02 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_remove_invoices_currency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotarahResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('message', models.TextField()),
                ('fotarah_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('qr_code_binary', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices')),
            ],
        ),
    ]
