# Generated by Django 5.2.11 on 2026-02-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_fotarahresponses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotarahResponse',
        ),
    ]
