# Generated by Django 4.2.7 on 2024-06-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_drivers_balance_alter_drivers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='drivers.drivers', to_field='number'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury', to='drivers.drivers', to_field='number'),
        ),
    ]
