# Generated by Django 4.2.7 on 2024-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_drivers_number_alter_invoices_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
