# Generated by Django 4.2.7 on 2024-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_drivers_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='invoice_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='treasury',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
