# Generated by Django 4.2.7 on 2024-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_rename_invoice_number_invoices_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
