# Generated by Django 4.2.7 on 2024-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_invoices_number_alter_treasury_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
