# Generated by Django 4.2.7 on 2024-06-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_invoices_number_alter_treasury_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='amount',
            new_name='tamount',
        ),
        migrations.AddField(
            model_name='invoices',
            name='idate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='irequire',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='itype',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='samount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udinar', models.IntegerField(blank=True, null=True)),
                ('ufils', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('adinar', models.IntegerField(blank=True, null=True)),
                ('afils', models.IntegerField(blank=True, null=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drivers.invoices', to_field='number')),
            ],
        ),
    ]
