# Generated by Django 4.2.7 on 2024-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_rename_amount_invoices_tamount_invoices_idate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='idate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='irequire',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='itype',
            new_name='type',
        ),
        migrations.AddField(
            model_name='invoices',
            name='car',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='require',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
