# Generated by Django 4.2.7 on 2024-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_rename_idate_invoices_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='tamount',
        ),
        migrations.AddField(
            model_name='invoices',
            name='dinar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='fils',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
