# Generated by Django 4.2.7 on 2024-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_remove_invoices_tamount_invoices_dinar_invoices_fils'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='tamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
