# Generated by Django 4.2.7 on 2024-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_invoices_tamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='driver_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
