# Generated by Django 4.2.7 on 2024-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_invoices_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
