# Generated by Django 4.2.7 on 2024-06-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_alter_invoices_date_alter_invoices_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='driver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
