# Generated by Django 4.2.7 on 2024-06-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_customers_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='number',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
