# Generated by Django 4.2.7 on 2024-06-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0017_remove_items_number_delete_invoices_delete_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='driver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
