# Generated by Django 4.2.7 on 2024-06-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0018_alter_treasury_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='password',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
