# Generated by Django 4.2.7 on 2024-06-25 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0020_alter_drivers_password_alter_drivers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='drivers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
