# Generated by Django 4.2.7 on 2024-06-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0022_alter_drivers_password_alter_drivers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='created_at',
        ),
    ]
