# Generated by Django 4.2.7 on 2024-06-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0025_alter_drivers_password_alter_drivers_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='symbol',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
