# Generated by Django 4.2.7 on 2024-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0026_remove_papers_symbol_delete_customers_delete_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
