# Generated by Django 4.2.7 on 2024-07-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0028_logs_alter_used_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.DeleteModel(
            name='Used_Vehicle',
        ),
    ]
