# Generated by Django 4.2.7 on 2024-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0029_delete_logs_delete_used_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='driver',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
