# Generated by Django 4.2.7 on 2024-08-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0030_alter_treasury_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='number',
        ),
        migrations.AlterField(
            model_name='drivers',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers'),
        ),
    ]
