# Generated by Django 4.2.7 on 2024-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0031_remove_drivers_number_alter_drivers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treasury',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
