# Generated by Django 4.2.7 on 2024-08-13 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_treasury_created_by'),
        ('drivers', '0032_drivers_created_by_treasury_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=50, null=True)),
                ('to_location', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('statement', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='SMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50, null=True)),
                ('car_num', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('mmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.mmission')),
            ],
        ),
    ]
