# Generated by Django 4.2.7 on 2024-08-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0033_mmission_smission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmission',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
