# Generated by Django 4.2.7 on 2024-08-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0034_mmission_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmission',
            name='phone',
        ),
    ]
