# Generated by Django 4.2.7 on 2024-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0035_remove_mmission_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmission',
            name='statement',
        ),
        migrations.AddField(
            model_name='mmission',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
