# Generated by Django 4.2.7 on 2024-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0036_remove_mmission_statement_mmission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='smission',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
