# Generated by Django 4.2.7 on 2024-08-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0037_smission_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='smission',
            name='car_mark',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
