# Generated by Django 4.2.7 on 2024-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0038_smission_car_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
