# Generated by Django 4.2.7 on 2024-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0039_alter_mmission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smission',
            name='receipt',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
