# Generated by Django 4.2.7 on 2024-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0040_smission_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmission',
            name='receipt',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
