# Generated by Django 4.2.7 on 2024-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0041_mmission_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmission',
            name='scost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
