# Generated by Django 4.2.7 on 2024-08-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0043_treasury_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmission',
            name='receipt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smission',
            name='receipt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
