# Generated by Django 4.2.7 on 2024-08-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_invoices_dinar_alter_invoices_fils_and_more'),
        ('drivers', '0044_alter_mmission_receipt_alter_smission_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_treasury', to='invoices.invoices'),
        ),
    ]
