# Generated by Django 4.2.7 on 2024-09-04 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_alter_customers_unique_together'),
        ('drivers', '0045_treasury_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=50, null=True)),
                ('to_location', models.CharField(blank=True, max_length=50, null=True)),
                ('car_type', models.CharField(max_length=50, null=True)),
                ('car_num', models.CharField(blank=True, max_length=50, null=True)),
                ('car_color', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('receipt', models.CharField(blank=True, max_length=20, null=True)),
                ('scost', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
        ),
    ]
