# Generated by Django 4.2.7 on 2024-09-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0046_pmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmission',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='pmission',
            name='count',
        ),
        migrations.RemoveField(
            model_name='pmission',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='pmission',
            name='scost',
        ),
    ]
