# Generated by Django 4.2.7 on 2024-09-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0047_remove_pmission_cost_remove_pmission_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmission',
            name='department',
        ),
    ]
