# Generated by Django 4.2.7 on 2024-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0048_remove_pmission_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmission',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
