# Generated by Django 4.2.7 on 2024-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0049_mmission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmission',
            name='car_mark',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
