# Generated by Django 4.2.7 on 2024-09-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0051_pmission_mmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmission',
            name='description',
        ),
    ]
