# Generated by Django 4.2.7 on 2024-09-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0052_remove_mmission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmission',
            name='count',
        ),
    ]
