# Generated by Django 4.2.7 on 2024-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0053_remove_mmission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmission',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mmission',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
