# Generated by Django 4.2.7 on 2024-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0054_mmission_count_mmission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmission',
            name='another_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
