# Generated by Django 4.2.7 on 2024-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0055_pmission_another_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmission',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
