# Generated by Django 4.2.7 on 2024-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0056_pmission_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmission',
            name='accept',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
