# Generated by Django 4.2.7 on 2024-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0057_mmission_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smission',
            name='receipt',
            field=models.CharField(blank=True, default='Assigned', max_length=20, null=True),
        ),
    ]
