# Generated by Django 5.1.4 on 2025-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0058_alter_smission_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='status',
            field=models.CharField(blank=True, default='Available', max_length=20, null=True),
        ),
    ]
