# Generated by Django 5.2.16 on 2026-07-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0059_drivers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
