# Generated by Django 4.2.7 on 2024-07-31 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_used_vehicle_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_vehicle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='vehicle_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='used_vehicle',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='used_vehicle',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
