# Generated by Django 4.2.7 on 2024-08-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_used_vehicle_created_at_used_vehicle_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='used_vehicle',
            old_name='vehicle_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='used_vehicle',
            old_name='vehicle_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='used_vehicle',
            old_name='vehicle_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
