# Generated by Django 4.2.7 on 2024-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_rename_vehicle_date_used_vehicle_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_vehicle',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
