# Generated by Django 4.2.7 on 2024-08-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_used_vehicle_expenses_used_vehicle_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_vehicle',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
