# Generated by Django 4.2.7 on 2024-09-09 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0054_mmission_count_mmission_description'),
        ('mobile', '0006_used_vehicle_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_meter', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.used_vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Auto_Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_meter', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('maintenance_center', models.CharField(blank=True, max_length=100, null=True)),
                ('oil_filter', models.BooleanField(null=True)),
                ('air_filter', models.BooleanField(null=True)),
                ('diesel_filter', models.BooleanField(null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.used_vehicle')),
            ],
        ),
    ]
