# Generated by Django 4.2.7 on 2024-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_fuel_filling_auto_oil'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_vehicle',
            name='air_filter_meter',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='current_air_filter_diff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='current_fuel_filter_diff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='current_oil_diff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='default_air_filter_diff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='default_fuel_filter_diff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='default_oil_diff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='default_oil_filter_diff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='fuel_filter_meter',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='fuel_meter',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='used_vehicle',
            name='oil_meter',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
