# Generated by Django 4.2.7 on 2024-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_used_vehicle_air_filter_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_vehicle',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
