# Generated by Django 4.2.7 on 2024-09-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_used_vehicle_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_oil',
            name='oil_filter',
        ),
    ]
