# Generated by Django 4.2.7 on 2024-09-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0010_remove_auto_oil_oil_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used_vehicle',
            name='default_oil_filter_diff',
        ),
    ]
