# Generated by Django 4.2.7 on 2024-09-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0011_remove_used_vehicle_default_oil_filter_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_oil',
            name='meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='oil/'),
        ),
        migrations.AddField(
            model_name='fuel_filling',
            name='meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/'),
        ),
    ]
