# Generated by Django 5.2.11 on 2026-02-11 14:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='card.customer'),
            preserve_default=False,
        ),
    ]
