# Generated by Django 5.2.11 on 2026-02-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_category_servicerequest_servicequota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicequota',
            name='expiration_date',
        ),
    ]
