# Generated by Django 5.2.11 on 2026-02-16 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_remove_servicequota_expiration_date'),
        ('drivers', '0059_drivers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='categorycard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='location_type',
            field=models.IntegerField(choices=[(1, 'Single Location'), (2, 'Pickup and Dropoff')], default=1),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RequsetMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=50, null=True)),
                ('to_location', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('receipt', models.CharField(blank=True, max_length=20, null=True)),
                ('scost', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('accept', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card.customer')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='card.servicerequest')),
            ],
        ),
    ]
