# Generated by Django 5.2.11 on 2026-02-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_remove_service_price_categorycard_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requsetmission',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.service'),
        ),
    ]
