# Generated by Django 5.2.11 on 2026-02-22 17:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_servicerequest_status_userlastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='requsetmission',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
