# Generated by Django 5.2.11 on 2026-02-22 17:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_requsetmission_phone_servicerequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='JO', unique=True),
        ),
        migrations.AlterField(
            model_name='requsetmission',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='JO'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='JO'),
        ),
    ]
