# Generated by Django 5.2.11 on 2026-02-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_customer_phone_alter_requsetmission_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requsetmission',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='phone',
            new_name='contact_phone',
        ),
    ]
