# Generated by Django 5.2.11 on 2026-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_rename_phone_requsetmission_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type_car',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
