# Generated by Django 5.2.11 on 2026-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_add_type_car_to_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color_car',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
