# Generated by Django 5.2.11 on 2026-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_add_color_car_to_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_quota',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
