# Generated by Django 5.2.11 on 2026-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_add_default_quota_to_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='default_quota',
        ),
        migrations.AddField(
            model_name='categorycard',
            name='default_quota',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
