# Generated by Django 5.2.11 on 2026-07-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_move_default_quota_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text="GPS accuracy in meters, as reported by the customer's device", null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
