# Generated by Django 5.2.16 on 2026-07-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_card_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='included_per_request',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Free allowance included in a single request, e.g. 50 km', max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_label',
            field=models.CharField(blank=True, help_text='e.g. km, liter — leave blank if this service is never billed by quantity', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price charged per unit beyond the included allowance. Leave 0 if this service has no per-unit charge.', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='used_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity used (e.g. km towed, liters filled), entered by staff on completion', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('used_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('included_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_label', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='card.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
