# Generated by Django 5.2.16 on 2026-07-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0018_service_included_per_request_service_unit_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='included_per_request',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit_label',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='used_amount',
        ),
    ]
