# Generated by Django 5.2.16 on 2026-07-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_remove_service_included_per_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='included_amount',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='unit_label',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='used_amount',
        ),
        migrations.AddField(
            model_name='requsetmission',
            name='cost_reason',
            field=models.CharField(blank=True, help_text="Reason for the additional cost, e.g. 'towing beyond included distance'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
