# Generated by Django 5.2.16 on 2026-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_remove_serviceinvoice_included_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_quota',
            field=models.PositiveIntegerField(blank=True, help_text="Overrides the category's default quota for this specific service when issuing a new card. Leave blank to use the category default.", null=True),
        ),
    ]
