# Generated by Django 5.2.16 on 2026-07-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_service_default_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='showroom',
            field=models.ForeignKey(blank=True, help_text='Leave blank for an individual card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='card.showroom'),
        ),
    ]
