# Generated by Django 5.2.16 on 2026-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0022_showroom_card_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requsetmission',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
