# Generated by Django 5.2.16 on 2026-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0024_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the card price has been paid'),
        ),
        migrations.AddField(
            model_name='card',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
