# Generated by Django 5.2.16 on 2026-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0025_card_is_paid_card_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cardholders/logos/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10),
        ),
    ]
