# Generated by Django 5.2.16 on 2026-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0026_customer_logo_customer_notes_customer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cliq', 'CliQ'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], max_length=20, null=True),
        ),
    ]
