# Generated by Django 5.2.16 on 2026-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0027_serviceinvoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='terms_ar',
            field=models.TextField(blank=True, help_text='الشروط والأحكام بالعربية - بند في كل سطر', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='terms_en',
            field=models.TextField(blank=True, help_text='Terms & Conditions in English - one condition per line', null=True),
        ),
    ]
