"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-!@#4$%5^&*()_+1234567890abcdefghijklmnopqrstuvwxyz")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'customers',
    'invoices',
    'drivers.apps.DriversConfig',
    'balances',
    'recipt_vouchers',
    'suppliers',
    'django_filters',
    'mobile',
    'drf_yasg',
    'channels',
    'phonenumber_field',
    'card',
    'sslserver'
    
    #'csp',
]
CSRF_TRUSTED_ORIGINS = [
    "https://127.0.0.1:8000",
    "https://localhost:8000",
    "https://192.168.1.2:8000",  # ضع IP جهازك
]

# Public HTTPS base address used to build the link encoded inside card QR codes.
# Change via env var once the app is reachable on a real domain.
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "https://192.168.1.2:8000")

# ──────────────────────────────────────────────
# Firebase Cloud Messaging (push notifications)
# ──────────────────────────────────────────────
# 1. Server-side: download a service account key from Firebase Console
#    (Project Settings > Service Accounts > Generate new private key) and save
#    it at the path below (gitignored). Sending silently no-ops until this exists.
FIREBASE_CREDENTIALS_PATH = os.getenv(
    "FIREBASE_CREDENTIALS_PATH", os.path.join(BASE_DIR, "firebase-service-account.json")
)
# 2. Client-side: the Web app config from Firebase Console (Project Settings >
#    General > Your apps > Web app). Not secret - safe to ship to the browser.
FIREBASE_WEB_CONFIG = {
    "apiKey": os.getenv("FIREBASE_API_KEY", "AIzaSyA7kZu4vmJwpRXynjB06suRjJfamRb9t7Q"),
    "authDomain": os.getenv("FIREBASE_AUTH_DOMAIN", "alroaya-crm.firebaseapp.com"),
    "projectId": os.getenv("FIREBASE_PROJECT_ID", "alroaya-crm"),
    "storageBucket": os.getenv("FIREBASE_STORAGE_BUCKET", "alroaya-crm.firebasestorage.app"),
    "messagingSenderId": os.getenv("FIREBASE_MESSAGING_SENDER_ID", "761319671828"),
    "appId": os.getenv("FIREBASE_APP_ID", "1:761319671828:web:c56ed755966579e7efff01"),
}
# 3. VAPID public key, from Project Settings > Cloud Messaging > Web Push certificates.
FIREBASE_VAPID_KEY = os.getenv(
    "FIREBASE_VAPID_KEY", "BF-QvB2UfkUoc-pAVLBWtObWuoRpZromZLzvPNR2BLnJ1OVWi69Zp6p38TU-5PiHbW3Dnn3E_-_AsNNEr5mlNhg"
)

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = False
ASGI_APPLICATION = 'project.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
'''
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",  # Allow inline styles (use with caution)
)

CSP_CONNECT_SRC = (
    "'self'",
    'ws://127.0.0.1',  # Add your WebSocket URL here
)
'''
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        }
    }
}

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'csp.middleware.CSPMiddleware',
    #'channels.middleware.BaseMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'card.context_processors.firebase_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'smtproject',
        'USER': 'postgres',
        'PASSWORD': 'mahm01142',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_ROOT = os.path.join(BASE_DIR, "static")
#STATIC_ROOT = '/var/www/static'
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "project/static")]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
   'DEFAULT_PERMISSION_CLASSES': [
       'rest_framework.permissions.IsAuthenticated',
   ],
   'DEFAULT_AUTHENTICATION_CLASSES': (
       'rest_framework.authentication.SessionAuthentication',
       'rest_framework.authentication.TokenAuthentication',
   )
}

import logging
from django.utils.log import DEFAULT_LOGGING

LOGGING = DEFAULT_LOGGING.copy()

LOGGING["loggers"]["django.server"]["level"] = "CRITICAL"


# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# جدولة المهام الدورية
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'deactivate-expired-cards-daily': {
        'task': 'card.tasks.deactivate_expired_cards',
        # 'schedule': crontab(hour=2, minute=0),  # كل يوم الساعة 2 صباحاً
        'schedule': crontab(minute='*/1'), 
    },
}