from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="suppliers_index"),
    path('get_invoices/', views.get_invoices, name='sget_invoices'),
    path('get_invoice_details/', views.get_invoice_details, name='sget_invoice_details'),
    path('add/', views.add_supplier, name='add_supplier'),
    path('edit/<int:id>/', views.edit_supplier, name='edit_supplier'),
    path('supplier_details/<int:id>/', views.supplier_details, name='supplier_details'),
    path('invoice_details/<int:supplier_id>/<int:invoice_id>/', views.invoice_details, name='invoice_details'),
    path('vehicle_details/<int:id>/', views.vehicle_details, name='vehicle_details'),
    path('add_treasury/', views.add_treasury, name='add_streasury'),
    path('edit_treasury/<int:id>/', views.edit_treasury, name="edit_streasury"),
    path('delete_treasury/<int:id>/', views.delete_treasury, name="delete_streasury"),
    path('add_invoice/', views.add_invoice, name='add_invoice'),
    path('export_invoice/<int:id>/', views.export_invoice, name='sexport_invoice'),
    path('export/<int:id>/<str:date_from>/<str:date_to>/', views.export_treasury, name='export_streasury'),
    path('pexport/<int:id>/<str:date_from>/<str:date_to>/', views.export_profit, name='export_profit'),
    path('fexport/<int:id>/<str:date_from>/<str:date_to>/', views.export_fuel, name='export_fuel'),
    path('add_item/', views.add_item, name="add_sitem"),
    path('edit_invoice/<int:id>/', views.edit_invoice, name="sedit_invoice"),
    path('delete_invoice/<int:id>/', views.delete_invoice, name="sdelete_invoice"),
    path('edit_item/<int:id>/', views.edit_item, name="edit_sitem"),
    path('delete_item/<int:id>/', views.delete_item, name="delete_sitem"),
    path('pocurement/', views.pocurement, name='procurement'),
    path('vehicles/', views.vehicles, name='vehicles'),
    path('add_vehicle/', views.add_vehicle, name="add_vehicle"),
    path('edit_vehicle/<int:id>/', views.edit_vehicle, name="edit_vehicle"),
    path('add_attachment/', views.add_attachment, name='add_sattachment'),
    path('edit_attachment/<int:id>/', views.edit_attachment, name='edit_sattachment'),
    path('delete_attachment/<int:id>/', views.delete_attachment, name='delete_sattachment'),
    path('balance/<int:id>/', views.supplier_balance, name="supplier_balance"),
    path('vehicle_balance/<int:id>/', views.vehicle_balance, name="vehicle_balance"),
    path('view_att/<int:id>/', views.view_att, name="view_att"),
    path('add_att/<int:id>/', views.add_att, name="add_att"),
    path('delete_att/<int:id>/', views.delete_att, name="delete_att"),
    path('sfetch_attachments/', views.sfetch_attachments, name='sfetch_attachments'),
    path('filter/<int:id>/', views.filter_invoices, name='sfilter_invoices'),
    path('vfilter/<int:id>/', views.vfilter_invoices, name='vfilter_invoices'),
    path('bfilter/<int:id>/', views.bfilter_invoices, name='bfilter_invoices'),
    path('fetch_attachments/', views.fetch_attachments, name='fetch_vattachments'),
]


