# Generated by Django 4.2.7 on 2024-06-26 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('phone', models.CharField(max_length=30, null=True, unique=True)),
                ('mail', models.CharField(max_length=50, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('payment', models.CharField(max_length=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ImageField(blank=True, upload_to='')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='customers.customers', to_field='symbol')),
            ],
        ),
    ]
