# Generated by Django 4.2.7 on 2024-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='logo',
            field=models.ImageField(blank=True, upload_to='customer_logos/'),
        ),
    ]
