# Generated by Django 4.2.7 on 2024-07-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='symbol',
        ),
        migrations.AddField(
            model_name='papers',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='papers',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='paper',
            field=models.ImageField(blank=True, upload_to='customer_papers/'),
        ),
    ]
