# Generated by Django 4.2.7 on 2024-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_papers_symbol_papers_description_papers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
