# Generated by Django 4.2.7 on 2024-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_treasury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasury',
            name='name',
        ),
        migrations.AddField(
            model_name='treasury',
            name='customer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
