# Generated by Django 4.2.7 on 2024-07-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_treasury_name_treasury_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
