# Generated by Django 4.2.7 on 2024-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customers_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='symbol',
        ),
    ]
