# Generated by Django 4.2.7 on 2024-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_customers_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
