# Generated by Django 4.2.7 on 2024-07-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customers_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_logos/'),
        ),
    ]
