# Generated by Django 4.2.7 on 2024-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customers_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper',
            field=models.ImageField(blank=True, null=True, upload_to='customer_papers/'),
        ),
    ]
