# Generated by Django 4.2.7 on 2024-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_papers_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='payment',
            field=models.CharField(default='نقدي', max_length=10, null=True),
        ),
    ]
