# Generated by Django 4.2.7 on 2024-07-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customers_balance_alter_customers_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
