# Generated by Django 4.2.7 on 2024-07-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='name',
        ),
        migrations.AddField(
            model_name='papers',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
