# Generated by Django 4.2.7 on 2024-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_remove_papers_name_papers_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='customer_pdfs/'),
        ),
    ]
