# Generated by Django 4.2.7 on 2024-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_papers_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
