# Generated by Django 4.2.7 on 2024-08-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_treasury_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
