# Generated by Django 4.2.7 on 2024-08-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_customers_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50, null=True)),
                ('car_mark', models.CharField(max_length=50, null=True)),
                ('car_num', models.CharField(blank=True, max_length=50, null=True)),
                ('car_color', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
        ),
    ]
