# Generated by Django 4.2.7 on 2024-08-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_customer_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='payment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
