# Generated by Django 4.2.7 on 2024-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_treasury_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
