# Generated by Django 4.2.7 on 2024-09-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_customers_password_customers_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('username', 'password')},
        ),
    ]
