# Generated by Django 4.2.7 on 2024-09-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_customers_name_alter_customers_password_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together=set(),
        ),
    ]
